package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao implements java.io.Serializable {

	private long id;
	private Venda venda;
	private String comentario;
	private Integer nota;

	public Avaliacao() {
	}

	public Avaliacao(long id, Venda venda) {
		this.id = id;
		this.venda = venda;
	}

	public Avaliacao(long id, Venda venda, String comentario, Integer nota) {
		this.id = id;
		this.venda = venda;
		this.comentario = comentario;
		this.nota = nota;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Venda getVenda() {
		return this.venda;
	}

	public void setVenda(Venda venda) {
		this.venda = venda;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Integer getNota() {
		return this.nota;
	}

	public void setNota(Integer nota) {
		this.nota = nota;
	}

}
