package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

/**
 * EnderecoComprador generated by hbm2java
 */
public class EnderecoComprador implements java.io.Serializable {

	private EnderecoCompradorId id;
	private Endereco endereco;
	private Comprador comprador;

	public EnderecoComprador() {
	}

	public EnderecoComprador(EnderecoCompradorId id, Endereco endereco, Comprador comprador) {
		this.id = id;
		this.endereco = endereco;
		this.comprador = comprador;
	}

	public EnderecoCompradorId getId() {
		return this.id;
	}

	public void setId(EnderecoCompradorId id) {
		this.id = id;
	}

	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	public Comprador getComprador() {
		return this.comprador;
	}

	public void setComprador(Comprador comprador) {
		this.comprador = comprador;
	}

}
