package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco implements java.io.Serializable {

	private long id;
	private String bairro;
	private String cep;
	private String complemento;
	private String estado;
	private String logradouro;
	private String municipio;
	private String numero;
	private Set vendas = new HashSet(0);
	private Set enderecoCompradors = new HashSet(0);

	public Endereco() {
	}

	public Endereco(long id) {
		this.id = id;
	}

	public Endereco(long id, String bairro, String cep, String complemento, String estado, String logradouro,
			String municipio, String numero, Set vendas, Set enderecoCompradors) {
		this.id = id;
		this.bairro = bairro;
		this.cep = cep;
		this.complemento = complemento;
		this.estado = estado;
		this.logradouro = logradouro;
		this.municipio = municipio;
		this.numero = numero;
		this.vendas = vendas;
		this.enderecoCompradors = enderecoCompradors;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Set getVendas() {
		return this.vendas;
	}

	public void setVendas(Set vendas) {
		this.vendas = vendas;
	}

	public Set getEnderecoCompradors() {
		return this.enderecoCompradors;
	}

	public void setEnderecoCompradors(Set enderecoCompradors) {
		this.enderecoCompradors = enderecoCompradors;
	}

}
