package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

/**
 * EnderecoCompradorId generated by hbm2java
 */
public class EnderecoCompradorId implements java.io.Serializable {

	private int compradorId;
	private int enderecoId;
	private short tipoEndereco;

	public EnderecoCompradorId() {
	}

	public EnderecoCompradorId(int compradorId, int enderecoId, short tipoEndereco) {
		this.compradorId = compradorId;
		this.enderecoId = enderecoId;
		this.tipoEndereco = tipoEndereco;
	}

	public int getCompradorId() {
		return this.compradorId;
	}

	public void setCompradorId(int compradorId) {
		this.compradorId = compradorId;
	}

	public int getEnderecoId() {
		return this.enderecoId;
	}

	public void setEnderecoId(int enderecoId) {
		this.enderecoId = enderecoId;
	}

	public short getTipoEndereco() {
		return this.tipoEndereco;
	}

	public void setTipoEndereco(short tipoEndereco) {
		this.tipoEndereco = tipoEndereco;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnderecoCompradorId))
			return false;
		EnderecoCompradorId castOther = (EnderecoCompradorId) other;

		return (this.getCompradorId() == castOther.getCompradorId())
				&& (this.getEnderecoId() == castOther.getEnderecoId())
				&& (this.getTipoEndereco() == castOther.getTipoEndereco());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCompradorId();
		result = 37 * result + this.getEnderecoId();
		result = 37 * result + this.getTipoEndereco();
		return result;
	}

}
