package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

/**
 * Estoque generated by hbm2java
 */
public class Estoque implements java.io.Serializable {

	private long id;
	private Produto produto;

	public Estoque() {
	}

	public Estoque(long id, Produto produto) {
		this.id = id;
		this.produto = produto;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

}
