package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto implements java.io.Serializable {

	private long id;
	private String descricao;
	private Float preco;
	private Float precoPromocional;
	private String titulo;
	private Set produtoImagems = new HashSet(0);
	private Set estoques = new HashSet(0);

	public Produto() {
	}

	public Produto(long id) {
		this.id = id;
	}

	public Produto(long id, String descricao, Float preco, Float precoPromocional, String titulo, Set produtoImagems,
			Set estoques) {
		this.id = id;
		this.descricao = descricao;
		this.preco = preco;
		this.precoPromocional = precoPromocional;
		this.titulo = titulo;
		this.produtoImagems = produtoImagems;
		this.estoques = estoques;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Float getPreco() {
		return this.preco;
	}

	public void setPreco(Float preco) {
		this.preco = preco;
	}

	public Float getPrecoPromocional() {
		return this.precoPromocional;
	}

	public void setPrecoPromocional(Float precoPromocional) {
		this.precoPromocional = precoPromocional;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Set getProdutoImagems() {
		return this.produtoImagems;
	}

	public void setProdutoImagems(Set produtoImagems) {
		this.produtoImagems = produtoImagems;
	}

	public Set getEstoques() {
		return this.estoques;
	}

	public void setEstoques(Set estoques) {
		this.estoques = estoques;
	}

}
