package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

/**
 * ProdutoImagem generated by hbm2java
 */
public class ProdutoImagem implements java.io.Serializable {

	private long id;
	private Produto produto;
	private String altText;
	private Long file;

	public ProdutoImagem() {
	}

	public ProdutoImagem(long id, Produto produto) {
		this.id = id;
		this.produto = produto;
	}

	public ProdutoImagem(long id, Produto produto, String altText, Long file) {
		this.id = id;
		this.produto = produto;
		this.altText = altText;
		this.file = file;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public String getAltText() {
		return this.altText;
	}

	public void setAltText(String altText) {
		this.altText = altText;
	}

	public Long getFile() {
		return this.file;
	}

	public void setFile(Long file) {
		this.file = file;
	}

}
