package com.data.first;
// Generated 20 de out. de 2024 15:41:43 by Hibernate Tools 6.5.1.Final

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor implements java.io.Serializable {

	private long id;
	private String name;

	public Vendedor() {
	}

	public Vendedor(long id) {
		this.id = id;
	}

	public Vendedor(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
